// =============================================
// SHERIFF GAMES - MOCK VERİLER
// Gerçek API'ye bağlanana kadar kullanılacak örnek veriler
// =============================================

export const MOCK_GAMES = [
  {
    id: '1',
    title: 'Cyber Legends',
    genre: 'RPG',
    price: 49.99,
    currency: 'TRY',
    rating: 4.7,
    reviewCount: 234,
    image: 'https://picsum.photos/seed/game1/400/250',
    screenshots: [
      'https://picsum.photos/seed/game1a/800/500',
      'https://picsum.photos/seed/game1b/800/500',
      'https://picsum.photos/seed/game1c/800/500',
    ],
    developer: 'NightOwl Studios',
    description: 'Siberpunk dünyasında geçen epik bir RPG macerası. Karakterini geliştir, düşmanlarınla savaş ve şehrin sırlarını keşfet.',
    tags: ['RPG', 'Açık Dünya', 'Çok Oyunculu', 'Siberpunk'],
    isFeatured: true,
    platform: 'PC',
  },
  {
    id: '2',
    title: 'Shadow Protocol',
    genre: 'Aksiyon',
    price: 29.99,
    currency: 'TRY',
    rating: 4.2,
    reviewCount: 89,
    image: 'https://picsum.photos/seed/game2/400/250',
    screenshots: [
      'https://picsum.photos/seed/game2a/800/500',
      'https://picsum.photos/seed/game2b/800/500',
    ],
    developer: 'StealthCode',
    description: 'Gizlilik tabanlı aksiyon oyunu. Düşmanlarını fark ettirmeden etkisiz hale getir.',
    tags: ['Aksiyon', 'Gizlilik', 'Strateji'],
    isFeatured: true,
    platform: 'PC',
  },
  {
    id: '3',
    title: 'Pixel Quest',
    genre: 'Platform',
    price: 0,
    currency: 'TRY',
    rating: 4.5,
    reviewCount: 512,
    image: 'https://picsum.photos/seed/game3/400/250',
    screenshots: [
      'https://picsum.photos/seed/game3a/800/500',
    ],
    developer: 'RetroWave Dev',
    description: 'Klasik platform oyunu modern dokunuşlarla. Ücretsiz oyna!',
    tags: ['Platform', 'Retro', 'Ücretsiz'],
    isFeatured: false,
    platform: 'PC & Mobil',
  },
  {
    id: '4',
    title: 'Void Runner',
    genre: 'Koşu',
    price: 14.99,
    currency: 'TRY',
    rating: 3.9,
    reviewCount: 67,
    image: 'https://picsum.photos/seed/game4/400/250',
    screenshots: [
      'https://picsum.photos/seed/game4a/800/500',
    ],
    developer: 'SpaceTime Games',
    description: 'Uzayda hız dolu bir koşu macerası.',
    tags: ['Koşu', 'Uzay', 'Hız'],
    isFeatured: false,
    platform: 'Mobil',
  },
  {
    id: '5',
    title: 'Dark Fortress',
    genre: 'Strateji',
    price: 79.99,
    currency: 'TRY',
    rating: 4.8,
    reviewCount: 1024,
    image: 'https://picsum.photos/seed/game5/400/250',
    screenshots: [
      'https://picsum.photos/seed/game5a/800/500',
      'https://picsum.photos/seed/game5b/800/500',
    ],
    developer: 'IronCastle Studios',
    description: 'Kale inşa et, ordunu yönet, imparatorluk kur.',
    tags: ['Strateji', 'İnşaat', 'Orta Çağ'],
    isFeatured: true,
    platform: 'PC',
  },
  {
    id: '6',
    title: 'Neon Drift',
    genre: 'Yarış',
    price: 24.99,
    currency: 'TRY',
    rating: 4.1,
    reviewCount: 178,
    image: 'https://picsum.photos/seed/game6/400/250',
    screenshots: [
      'https://picsum.photos/seed/game6a/800/500',
    ],
    developer: 'TurboLabs',
    description: 'Neon ışıklı şehirlerde adrenalin dolu yarışlar.',
    tags: ['Yarış', 'Neon', 'Çok Oyunculu'],
    isFeatured: false,
    platform: 'PC & Konsol',
  },
];

export const MOCK_ASSETS = [
  {
    id: 'a1',
    title: 'Fantasy Character Pack',
    type: 'Karakter',
    price: 149.99,
    currency: 'TRY',
    rating: 4.6,
    reviewCount: 45,
    image: 'https://picsum.photos/seed/asset1/400/250',
    developer: 'ArtForge',
    description: '20 adet yüksek kaliteli fantezi karakter sprite seti.',
    tags: ['2D', 'Karakter', 'Fantezi', 'Sprite'],
    fileFormat: 'PNG, PSD',
    fileSize: '250 MB',
  },
  {
    id: 'a2',
    title: 'Sci-Fi UI Kit',
    type: 'UI',
    price: 89.99,
    currency: 'TRY',
    rating: 4.9,
    reviewCount: 120,
    image: 'https://picsum.photos/seed/asset2/400/250',
    developer: 'PixelLab',
    description: 'Bilim kurgu temalı arayüz bileşenleri paketi.',
    tags: ['UI', 'Sci-Fi', 'Vector'],
    fileFormat: 'SVG, AI',
    fileSize: '45 MB',
  },
  {
    id: 'a3',
    title: 'Epic Sound Pack',
    type: 'Ses',
    price: 0,
    currency: 'TRY',
    rating: 4.3,
    reviewCount: 89,
    image: 'https://picsum.photos/seed/asset3/400/250',
    developer: 'SoundWave',
    description: '100+ oyun efekti ve müzik dosyası. Ücretsiz!',
    tags: ['Ses', 'Müzik', 'Efekt', 'Ücretsiz'],
    fileFormat: 'MP3, WAV',
    fileSize: '180 MB',
  },
];

export const MOCK_COMMENTS = [
  {
    id: 'c1',
    username: 'GamerPro42',
    avatar: 'https://picsum.photos/seed/user1/50/50',
    rating: 5,
    text: 'Harika bir oyun! Kesinlikle tavsiye ederim.',
    date: '12 Haziran 2025',
  },
  {
    id: 'c2',
    username: 'PixelKnight',
    avatar: 'https://picsum.photos/seed/user2/50/50',
    rating: 4,
    text: 'Grafikleri çok iyi ama hikaye biraz kısa kalıyor.',
    date: '8 Haziran 2025',
  },
  {
    id: 'c3',
    username: 'NightOwl_99',
    avatar: 'https://picsum.photos/seed/user3/50/50',
    rating: 4,
    text: 'Çok oyunculu modu gerçekten eğlenceli.',
    date: '2 Haziran 2025',
  },
];

export const DASHBOARD_STATS = {
  totalSales: 1248,
  totalRevenue: 47320,
  totalProducts: 5,
  totalReviews: 89,
  monthlyData: [
    { month: 'Oca', revenue: 3200 },
    { month: 'Şub', revenue: 4100 },
    { month: 'Mar', revenue: 3800 },
    { month: 'Nis', revenue: 5200 },
    { month: 'May', revenue: 6100 },
    { month: 'Haz', revenue: 7400 },
  ],
  notifications: [
    { id: 'n1', text: 'Cyber Legends için yeni bir yorum yapıldı.', type: 'info' },
    { id: 'n2', text: 'Shadow Protocol satışlarınız %20 arttı!', type: 'success' },
    { id: 'n3', text: 'Pixel Quest indirim kampanyası sona eriyor.', type: 'warning' },
  ],
};